In [4]:
import pandas as pd

df = pd.read_csv("../../data/sample_data/train_3.csv")

In [5]:
df.head()

,855.144865868006,847.292061506786,824.731660406105,866.64540600304,928.333300035969,927.649280359846,901.072254821959,940.843420025213,954.740175823436,960.653429083165,...,1562.59924164802,1655.36384538449,1522.98878747559,1626.02824335177,1524.9635718672,1611.94304453833,1600.2298640262,1665.00092848864,1554.96685838367,1592.16733774914
0,496.999629,491.266202,514.497083,505.818719,523.568994,525.329842,529.642170,528.609020,531.297717,518.131913,...,708.921393,721.355277,691.860173,716.567723,725.964129,700.485850,733.510557,724.657713,729.666164,738.639880
1,1333.548021,1370.089237,1415.076738,1281.416912,1358.059752,1384.964713,1276.752289,1321.857572,1334.174304,1305.352087,...,820.205800,786.384157,831.653971,821.638892,806.679814,776.258484,800.773122,793.991049,737.549365,758.503816
2,601.167280,541.750384,601.225895,561.288487,543.068962,560.192329,585.670783,563.629411,624.889591,550.727764,...,881.624556,852.173314,859.787236,886.969227,844.393601,859.741009,894.169290,931.148912,901.802749,982.955780
3,507.766151,498.915098,513.571657,507.190113,510.092496,506.453491,514.185068,510.417658,514.088633,492.939973,...,531.063462,537.049600,518.477909,533.704537,505.416179,529.780744,529.286141,532.815943,527.535573,522.813344
4,1297.442198,1336.300224,1278.909364,1296.703092,1307.259151,1307.682832,1334.964897,1312.122833,1389.214994,1326.777517,...,1106.913966,978.056317,1007.656784,979.999586,1028.994232,937.895421,952.296501,952.349756,875.623717,902.942337